import type { CategorySummary, FaqItem, GalleryMediaItem, Testimonial } from '../../types/api';
import type { Product } from '../../types/product';

export const MOCK_CATEGORIES: CategorySummary[] = [
  {
    id: 'cat-1',
    name: { es: 'Panadería Ecuatoriana', en: 'Ecuadorian Bakery' },
    slug: { es: 'panaderia-ecuatoriana', en: 'ecuadorian-bakery' },
    description: {
      es: 'Panes recién horneados con recetas ancestrales de Ambato y Ecuador.',
      en: 'Freshly baked bread crafted with traditional recipes from Ambato and Ecuador.',
    },
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
    displayOrder: 1,
    productCount: 8,
  },
  {
    id: 'cat-2',
    name: { es: 'Pasteles Personalizados', en: 'Custom Cakes' },
    slug: { es: 'pasteles-personalizados', en: 'custom-cakes' },
    description: {
      es: 'Diseños únicos y sabores inolvidables para bodas, cumpleaños y eventos.',
      en: 'Unique custom designs and unforgettable flavors for weddings and birthdays.',
    },
    imageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=800&auto=format&fit=crop&q=80',
    displayOrder: 2,
    productCount: 6,
  },
  {
    id: 'cat-3',
    name: { es: 'Postres y Dulces Tradicionales', en: 'Traditional Desserts' },
    slug: { es: 'postres-y-dulces', en: 'desserts-sweets' },
    description: {
      es: 'Tres leches, roseros, quesadillas y dulces autóctonos del Ecuador.',
      en: 'Tres leches, roseros, quesadillas, and authentic Ecuadorian sweet treats.',
    },
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=80',
    displayOrder: 3,
    productCount: 7,
  },
  {
    id: 'cat-4',
    name: { es: 'Bocaditos y Catering', en: 'Snacks & Catering' },
    slug: { es: 'bocaditos-y-fiestas', en: 'party-snacks' },
    description: {
      es: 'Empanaditas, hojaldres y bocadillos salados y dulces para tus fiestas.',
      en: 'Mini empanadas, pastries, and savory or sweet snacks for parties.',
    },
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&auto=format&fit=crop&q=80',
    displayOrder: 4,
    productCount: 5,
  },
  {
    id: 'cat-5',
    name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' },
    slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' },
    description: {
      es: 'Productos importados de Ecuador, chocolates, café y más.',
      en: 'Imported products from Ecuador, coffees, chocolates, and groceries.',
    },
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
    displayOrder: 5,
    productCount: 4,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    sku: 'PAN-AMB-01',
    name: { es: 'Allullas Ambateñas (Fundita 6 u.)', en: 'Ambato Allullas (Pack of 6)' },
    slug: { es: 'allullas-ambatenas', en: 'ambato-allullas' },
    shortDescription: {
      es: 'Crujientes allullas de manteca de cerdo y harina de primera, horneadas diariamente.',
      en: 'Crispy pork lard allullas baked daily following Ambato tradition.',
    },
    description: {
      es: 'Las tradicionales allullas de Ambato elaboradas con masa hojaldrada salada. Perfectas para acompañar el chocolate caliente o el café de la mañana.',
      en: 'Traditional Ambato allullas made with flaky savory dough. Perfect with hot cocoa or morning coffee.',
    },
    primaryCategory: {
      id: 'cat-1',
      name: { es: 'Panadería Ecuatoriana', en: 'Ecuadorian Bakery' },
      slug: { es: 'panaderia-ecuatoriana', en: 'ecuadorian-bakery' },
    },
    categories: [
      { id: 'cat-1', name: { es: 'Panadería Ecuatoriana', en: 'Ecuadorian Bakery' }, slug: { es: 'panaderia-ecuatoriana', en: 'ecuadorian-bakery' } },
    ],
    productType: 'simple',
    basePriceCents: 450,
    compareAtPriceCents: 500,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-1',
        publicId: 'trigal/allullas-1',
        secureUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Fundita de Allullas Ambateñas recién horneadas', en: 'Pack of freshly baked Ambato Allullas' },
        isPrimary: true,
      },
    ],
    ingredients: {
      es: 'Harina de trigo enriquecida, manteca de cerdo refinada, agua, sal de mar, levadura fresca.',
      en: 'Enriched wheat flour, refined pork lard, water, sea salt, fresh yeast.',
    },
    allergens: ['gluten'],
    dietaryTags: ['Artesanal', 'Tradicional Ambateño'],
    availability: {
      isAvailable: true,
      leadTimeDays: 0,
    },
    ordering: {
      allowDirectCall: true,
      allowDoorDash: true,
      allowCustomQuote: false,
    },
    tags: ['pan ecuatoriano', 'ambato', 'allulla', 'recien horneado'],
    featured: true,
    bestSeller: true,
    newProduct: false,
    seo: {
      title: { es: 'Allullas Ambateñas en Orange, NJ | El Trigal Bakery', en: 'Ambato Allullas in Orange, NJ | El Trigal Bakery' },
      description: { es: 'Compra allullas ambateñas frescas horneadas diariamente en Orange, NJ.', en: 'Buy fresh Ambato allullas baked daily in Orange, NJ.' },
      keywords: ['allullas', 'pan ambateño', 'pan ecuatoriano orange nj'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-2',
    sku: 'EMP-VIE-01',
    name: { es: 'Empanada de Viento con Queso', en: 'Cheese Wind Empanada (Empanada de Viento)' },
    slug: { es: 'empanada-de-viento', en: 'cheese-wind-empanada' },
    shortDescription: {
      es: 'Gigante empanada inflada rellena de queso fresco derretido y espolvoreada con azúcar.',
      en: 'Giant puffed fried empanada filled with melted fresh cheese and dusted with sugar.',
    },
    description: {
      es: 'Espectacular empanada de viento tradicional ecuatoriana. Su masa fina y crujiente se infla al freírse y se sirve caliente con su toque dulce característico.',
      en: 'Spectacular traditional Ecuadorian wind empanada. Crispy thin dough puffs up when fried, filled with melted white cheese and sprinkled with granulated sugar.',
    },
    primaryCategory: {
      id: 'cat-1',
      name: { es: 'Panadería Ecuatoriana', en: 'Ecuadorian Bakery' },
      slug: { es: 'panaderia-ecuatoriana', en: 'ecuadorian-bakery' },
    },
    categories: [
      { id: 'cat-1', name: { es: 'Panadería Ecuatoriana', en: 'Ecuadorian Bakery' }, slug: { es: 'panaderia-ecuatoriana', en: 'ecuadorian-bakery' } },
      { id: 'cat-4', name: { es: 'Bocaditos y Catering', en: 'Snacks & Catering' }, slug: { es: 'bocaditos-y-fiestas', en: 'party-snacks' } },
    ],
    productType: 'simple',
    basePriceCents: 350,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-2',
        publicId: 'trigal/empanada-viento-1',
        secureUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Empanada de viento ecuatoriana crujiente con azúcar', en: 'Crispy Ecuadorian wind empanada with sugar' },
        isPrimary: true,
      },
    ],
    ingredients: {
      es: 'Harina de trigo, queso fresco ecuatoriano, mantequilla, polvo de hornear, azúcar.',
      en: 'Wheat flour, fresh Ecuadorian cheese, butter, baking powder, sugar.',
    },
    allergens: ['gluten', 'dairy'],
    dietaryTags: ['Vegetariano'],
    availability: {
      isAvailable: true,
      leadTimeDays: 0,
    },
    ordering: {
      allowDirectCall: true,
      allowDoorDash: true,
      allowCustomQuote: false,
    },
    tags: ['empanada de viento', 'queso fresco', 'bocadito ecuatoriano'],
    featured: true,
    bestSeller: true,
    newProduct: false,
    seo: {
      title: { es: 'Empanadas de Viento en Orange, NJ | El Trigal', en: 'Cheese Wind Empanadas in Orange, NJ | El Trigal' },
      description: { es: 'Prueba la mejor empanada de viento con queso derretido en Orange, NJ.', en: 'Taste the best cheese wind empanada in Orange, NJ.' },
      keywords: ['empanada de viento', 'empanada ecuatoriana orange nj'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-3',
    sku: 'PAS-3LE-01',
    name: { es: 'Pastel de Tres Leches Tradicional', en: 'Traditional Tres Leches Cake' },
    slug: { es: 'pastel-tres-leches', en: 'tres-leches-cake' },
    shortDescription: {
      es: 'Bizcocho ultra húmedo bañado en tres leches con crema chantilly y duraznos o fresas.',
      en: 'Ultra-moist sponge cake soaked in three milks with whipped cream and fruit.',
    },
    description: {
      es: 'Nuestro aclamado pastel Tres Leches preparado con la receta clásica. Bizcocho esponjoso bañado generosamente en mezcla de leche condensada, evaporada y crema de leche.',
      en: 'Our acclaimed classic Tres Leches cake. Fluffy sponge cake generously soaked in evaporated milk, condensed milk, and heavy cream, topped with homemade whipped cream.',
    },
    primaryCategory: {
      id: 'cat-2',
      name: { es: 'Pasteles Personalizados', en: 'Custom Cakes' },
      slug: { es: 'pasteles-personalizados', en: 'custom-cakes' },
    },
    categories: [
      { id: 'cat-2', name: { es: 'Pasteles Personalizados', en: 'Custom Cakes' }, slug: { es: 'pasteles-personalizados', en: 'custom-cakes' } },
      { id: 'cat-3', name: { es: 'Postres y Dulces Tradicionales', en: 'Traditional Desserts' }, slug: { es: 'postres-y-dulces', en: 'desserts-sweets' } },
    ],
    productType: 'variable',
    basePriceCents: 3500,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: { es: 'Desde $35.00', en: 'From $35.00' },
    variants: [
      { id: 'var-1', sku: 'PAS-3LE-8', name: { es: 'Mediano (8-10 porciones)', en: 'Medium (8-10 servings)' }, priceCents: 3500, compareAtPriceCents: null, servings: 10, available: true },
      { id: 'var-2', sku: 'PAS-3LE-15', name: { es: 'Grande (15-20 porciones)', en: 'Large (15-20 servings)' }, priceCents: 5500, compareAtPriceCents: null, servings: 20, available: true },
    ],
    options: [],
    media: [
      {
        id: 'med-3',
        publicId: 'trigal/tres-leches-1',
        secureUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Pastel Tres Leches decorado con fresas frescas', en: 'Tres Leches Cake decorated with fresh strawberries' },
        isPrimary: true,
      },
    ],
    ingredients: {
      es: 'Leche evaporada, leche condensada, crema de leche, huevos de granja, harina de trigo, vainilla, fruta fresca.',
      en: 'Evaporated milk, condensed milk, heavy cream, farm eggs, wheat flour, vanilla, fresh fruit.',
    },
    allergens: ['gluten', 'dairy', 'eggs'],
    dietaryTags: ['Receta Tradicional'],
    availability: {
      isAvailable: true,
      leadTimeDays: 1,
    },
    ordering: {
      allowDirectCall: true,
      allowDoorDash: true,
      allowCustomQuote: true,
    },
    tags: ['tres leches', 'pastel de cumpleaños', 'postre ecuatoriano'],
    featured: true,
    bestSeller: true,
    newProduct: false,
    seo: {
      title: { es: 'Pastel Tres Leches en Orange, NJ | El Trigal', en: 'Tres Leches Cake in Orange, NJ | El Trigal' },
      description: { es: 'Encarga el mejor pastel tres leches artesanal en Orange, NJ.', en: 'Order the best artisanal tres leches cake in Orange, NJ.' },
      keywords: ['tres leches orange nj', 'pasteles de cumpleanos orange'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-4',
    sku: 'QUE-AMB-01',
    name: { es: 'Quesadillas Ambateñas (Caja 4 u.)', en: 'Ambato Quesadillas (Box of 4)' },
    slug: { es: 'quesadillas-ambatenas', en: 'ambato-quesadillas' },
    shortDescription: {
      es: 'Estrella pentagonal de masa fina rellena con suave crema dulce de queso y almidón de achira.',
      en: 'Star-shaped pastry filled with sweet cheese cream and achira starch.',
    },
    description: {
      es: 'Icono del patrimonio gastronómico de Ambato. Masa delgada doblada en cinco puntas rellena de una mezcla esponjosa de yemas, queso fresco sin sal, azúcar y almidón fino.',
      en: 'Iconic Ambato culinary heritage item. Thin dough folded into five points filled with a light whipped mixture of egg yolks, unsalted fresh cheese, sugar, and achira starch.',
    },
    primaryCategory: {
      id: 'cat-3',
      name: { es: 'Postres y Dulces Tradicionales', en: 'Traditional Desserts' },
      slug: { es: 'postres-y-dulces', en: 'desserts-sweets' },
    },
    categories: [
      { id: 'cat-3', name: { es: 'Postres y Dulces Tradicionales', en: 'Traditional Desserts' }, slug: { es: 'postres-y-dulces', en: 'desserts-sweets' } },
      { id: 'cat-1', name: { es: 'Panadería Ecuatoriana', en: 'Ecuadorian Bakery' }, slug: { es: 'panaderia-ecuatoriana', en: 'ecuadorian-bakery' } },
    ],
    productType: 'simple',
    basePriceCents: 800,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-4',
        publicId: 'trigal/quesadilla-1',
        secureUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Quesadillas ambateñas tradicionales horneadas', en: 'Baked traditional Ambato quesadillas' },
        isPrimary: true,
      },
    ],
    ingredients: {
      es: 'Queso artesanal, almidón de achira, azúcar, yemas de huevo, harina de trigo refinada.',
      en: 'Artisanal cheese, achira starch, sugar, egg yolks, refined wheat flour.',
    },
    allergens: ['gluten', 'dairy', 'eggs'],
    dietaryTags: ['Patrimonio Ambateño'],
    availability: {
      isAvailable: true,
      leadTimeDays: 0,
    },
    ordering: {
      allowDirectCall: true,
      allowDoorDash: true,
      allowCustomQuote: false,
    },
    tags: ['quesadilla ambateña', 'postre ecuatoriano', 'ambato'],
    featured: true,
    bestSeller: false,
    newProduct: true,
    seo: {
      title: { es: 'Quesadillas Ambateñas en New Jersey | El Trigal', en: 'Ambato Quesadillas in New Jersey | El Trigal' },
      description: { es: 'Quesadillas ambateñas autóctonas horneadas en Orange, NJ.', en: 'Authentic Ambato quesadillas baked in Orange, NJ.' },
      keywords: ['quesadilla ambateña', 'dulces ecuatorianos orange nj'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-5',
    sku: 'PAS-CUS-01',
    name: { es: 'Pastel Personalizado de Eventos', en: 'Custom Event Cake' },
    slug: { es: 'pastel-personalizado-eventos', en: 'custom-event-cake' },
    shortDescription: {
      es: 'Pasteles de alta pastelería diseñados a medida para bodas, quinceañeras y cumpleaños.',
      en: 'Custom designed high-end cakes for weddings, quinceañeras, and birthdays.',
    },
    description: {
      es: 'Creamos pasteles únicos adaptados a la temática y paleta de colores de tu celebración. Cobertura en fondant de vainilla o merengue italiano con bizcochos húmedos y rellenos gourmet.',
      en: 'We create bespoke cakes tailored to your celebration theme and color palette. Premium fondant or Italian meringue frosting with moist cake bases and gourmet fillings.',
    },
    primaryCategory: {
      id: 'cat-2',
      name: { es: 'Pasteles Personalizados', en: 'Custom Cakes' },
      slug: { es: 'pasteles-personalizados', en: 'custom-cakes' },
    },
    categories: [
      { id: 'cat-2', name: { es: 'Pasteles Personalizados', en: 'Custom Cakes' }, slug: { es: 'pasteles-personalizados', en: 'custom-cakes' } },
    ],
    productType: 'custom',
    basePriceCents: 8500,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: { es: 'Cotización según diseño', en: 'Quoted per design' },
    variants: [],
    options: [],
    media: [
      {
        id: 'med-5',
        publicId: 'trigal/custom-cake-1',
        secureUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Pastel personalizado de boda de 3 pisos con flores', en: '3-tier custom wedding cake with flowers' },
        isPrimary: true,
      },
    ],
    ingredients: null,
    allergens: ['gluten', 'dairy', 'eggs'],
    dietaryTags: ['100% Personalizado'],
    availability: {
      isAvailable: true,
      leadTimeDays: 5,
      customNotice: { es: 'Requiere al menos 5 días de anticipación.', en: 'Requires at least 5 days advance notice.' },
    },
    ordering: {
      allowDirectCall: true,
      allowDoorDash: false,
      allowCustomQuote: true,
    },
    tags: ['pastel de boda', 'pastel personalizado', 'pasteleria fina orange nj'],
    featured: true,
    bestSeller: true,
    newProduct: false,
    seo: {
      title: { es: 'Pasteles Personalizados en Orange, NJ | El Trigal', en: 'Custom Cakes in Orange, NJ | El Trigal' },
      description: { es: 'Encarga tu pastel personalizado para boda o cumpleaños en Orange, NJ.', en: 'Order your custom cake for wedding or birthday in Orange, NJ.' },
      keywords: ['pasteles personalizados orange nj', 'custom cakes essex county'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-6',
    sku: 'LAC-YOG-01',
    name: { es: 'Yogur Ecuatoriano Tradicional (1 Litro)', en: 'Traditional Ecuadorian Yogurt (1 Liter)' },
    slug: { es: 'yogur-ecuatoriano-tradicional', en: 'traditional-ecuadorian-yogurt' },
    shortDescription: {
      es: 'Cremoso yogur natural artesanal estilo ecuatoriano en sabores mora, durazno y maracuyá.',
      en: 'Creamy artisanal natural yogurt in blackberry, peach, and passion fruit flavors.',
    },
    description: {
      es: 'Auténtico yogur ecuatoriano preparado con leche fresca de granja y pulpa de fruta natural. Disponible en mora de Castilla, maracuyá y durazno.',
      en: 'Authentic Ecuadorian yogurt made with fresh farm milk and natural fruit pulp. Available in blackberry, passion fruit, and peach.',
    },
    primaryCategory: {
      id: 'cat-5',
      name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' },
      slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' },
    },
    categories: [
      { id: 'cat-5', name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' }, slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' } },
    ],
    productType: 'simple',
    basePriceCents: 650,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-6',
        publicId: 'trigal/yogur-1',
        secureUrl: 'https://images.unsplash.com/photo-1571212515416-fef01fc43637?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Yogur ecuatoriano artesanal de mora y maracuyá', en: 'Artisanal Ecuadorian yogurt' },
        isPrimary: true,
      },
    ],
    ingredients: { es: 'Leche entera pasteurizada, cultivos lácticos, pulpa natural de fruta, azúcar.', en: 'Whole pasteurized milk, active cultures, fruit pulp, sugar.' },
    allergens: ['dairy'],
    dietaryTags: ['Lácteos', 'Artesanal'],
    availability: { isAvailable: true, leadTimeDays: 0 },
    ordering: { allowDirectCall: true, allowDoorDash: true, allowCustomQuote: false },
    tags: ['yogur ecuatoriano', 'lacteos ecuador', 'yogur de mora', 'productos ecuatorianos'],
    featured: true,
    bestSeller: true,
    newProduct: true,
    seo: {
      title: { es: 'Yogur Ecuatoriano en Orange, NJ | El Trigal', en: 'Ecuadorian Yogurt in Orange, NJ | El Trigal' },
      description: { es: 'Compra yogur ecuatoriano natural artesanal de mora y maracuyá en Orange, NJ.', en: 'Buy fresh Ecuadorian yogurt in Orange, NJ.' },
      keywords: ['yogur ecuatoriano', 'lacteos ecuador orange nj'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-7',
    sku: 'LAC-QUE-01',
    name: { es: 'Queso Fresco Ecuatoriano / Manaba (Libra)', en: 'Fresh Ecuadorian / Manaba Cheese (Pound)' },
    slug: { es: 'queso-fresco-ecuatoriano', en: 'fresh-ecuadorian-cheese' },
    shortDescription: {
      es: 'Queso blanco artesanal de mesa, suave y bajo en sal, ideal para acompañar allullas o maduros.',
      en: 'Fresh white artisanal cheese, perfect to accompany allullas or sweet plantains.',
    },
    description: {
      es: 'Queso fresco artesanal elaborado según la receta tradicional manabita y sierrena. Textura suave, sabor lácteo puro y punto perfecto de sal.',
      en: 'Artisanal fresh cheese prepared following traditional Manabí and Sierra recipes. Soft texture, pure dairy flavor, and balanced salt.',
    },
    primaryCategory: {
      id: 'cat-5',
      name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' },
      slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' },
    },
    categories: [
      { id: 'cat-5', name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' }, slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' } },
    ],
    productType: 'simple',
    basePriceCents: 799,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-7',
        publicId: 'trigal/queso-1',
        secureUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Queso fresco ecuatoriano artesanal', en: 'Fresh Ecuadorian artisanal cheese' },
        isPrimary: true,
      },
    ],
    ingredients: { es: 'Leche entera de vaca, cuajo natural, sal marina.', en: 'Whole cow milk, natural rennet, sea salt.' },
    allergens: ['dairy'],
    dietaryTags: ['Lácteos', 'Sin Gluten'],
    availability: { isAvailable: true, leadTimeDays: 0 },
    ordering: { allowDirectCall: true, allowDoorDash: true, allowCustomQuote: false },
    tags: ['queso fresco', 'queso manaba', 'lacteos ecuador', 'queso ecuatoriano'],
    featured: true,
    bestSeller: true,
    newProduct: false,
    seo: {
      title: { es: 'Queso Fresco Ecuatoriano Manaba en Orange, NJ | El Trigal', en: 'Fresh Ecuadorian Cheese in Orange, NJ | El Trigal' },
      description: { es: 'Disfruta de auténtico queso fresco manaba ecuatoriano en Orange, NJ.', en: 'Enjoy authentic fresh Manaba cheese in Orange, NJ.' },
      keywords: ['queso manaba', 'queso fresco ecuatoriano orange nj'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-8',
    sku: 'DUL-MAN-01',
    name: { es: 'Manjar Blanco Tradicional Ecuatoriano (Tarro 500g)', en: 'Traditional Ecuadorian Manjar Blanco (500g Jar)' },
    slug: { es: 'manjar-blanco-tradicional', en: 'traditional-manjar-blanco' },
    shortDescription: {
      es: 'Dulce de leche artesanal ecuatoriano, cremoso y cocinado a fuego lento.',
      en: 'Artisanal Ecuadorian dulce de leche, slow cooked to creamy perfection.',
    },
    description: {
      es: 'Auténtico manjar de leche preparado a fuego lento con leche entera pura y azúcar. Ideal para untar en pan de almidón, bizcochos de Cayambe o galletas.',
      en: 'Authentic manjar de leche slow cooked with pure whole milk and sugar. Ideal for spread on cassava bread, Cayambe biscuits, or pastries.',
    },
    primaryCategory: {
      id: 'cat-5',
      name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' },
      slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' },
    },
    categories: [
      { id: 'cat-5', name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' }, slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' } },
    ],
    productType: 'simple',
    basePriceCents: 550,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-8',
        publicId: 'trigal/manjar-1',
        secureUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Tarro de manjar blanco ecuatoriano cremoso', en: 'Jar of creamy Ecuadorian manjar' },
        isPrimary: true,
      },
    ],
    ingredients: { es: 'Leche entera de vaca, azúcar blanca refinada, esencia de vainilla, bicarbonato de sodio.', en: 'Whole cow milk, refined white sugar, vanilla, baking soda.' },
    allergens: ['dairy'],
    dietaryTags: ['Dulces Tradicionales'],
    availability: { isAvailable: true, leadTimeDays: 0 },
    ordering: { allowDirectCall: true, allowDoorDash: true, allowCustomQuote: false },
    tags: ['manjar blanco', 'dulce de leche ecuador', 'dulces ecuatorianos'],
    featured: true,
    bestSeller: true,
    newProduct: false,
    seo: {
      title: { es: 'Manjar Blanco Ecuatoriano en Orange, NJ | El Trigal', en: 'Ecuadorian Manjar Blanco in Orange, NJ | El Trigal' },
      description: { es: 'Compra manjar blanco tradicional ecuatoriano casero en Orange, NJ.', en: 'Buy traditional Ecuadorian manjar blanco in Orange, NJ.' },
      keywords: ['manjar ecuatoriano', 'dulce de leche ecuador orange nj'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-9',
    sku: 'DUL-CHO-01',
    name: { es: 'Chocolates Finos de Aroma de Manabí (Barra 100g)', en: 'Fine Aroma Manabí Chocolate (100g Bar)' },
    slug: { es: 'chocolates-finos-manabi', en: 'fine-manabi-chocolate' },
    shortDescription: {
      es: 'Chocolate ecuatoriano de cacao fino de aroma 70% con notas florales y frutales.',
      en: '70% Ecuadorian fine aroma cacao chocolate bar with floral and fruity notes.',
    },
    description: {
      es: 'Barra de chocolate gourmet elaborado con los mejores granos de cacao Arriba Nacional cultivados en Manabí. Orgullo ecuatoriano premiado internacionalmente.',
      en: 'Gourmet chocolate bar crafted with top-grade Arriba Nacional cacao beans grown in Manabí. Internationally awarded Ecuadorian pride.',
    },
    primaryCategory: {
      id: 'cat-5',
      name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' },
      slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' },
    },
    categories: [
      { id: 'cat-5', name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' }, slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' } },
    ],
    productType: 'simple',
    basePriceCents: 499,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-9',
        publicId: 'trigal/chocolate-1',
        secureUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Barra de chocolate negro ecuatoriano fino de aroma', en: 'Ecuadorian fine aroma dark chocolate bar' },
        isPrimary: true,
      },
    ],
    ingredients: { es: 'Cacao fino de aroma de Ecuador (70%), manteca de cacao, azúcar orgánica.', en: 'Ecuadorian fine aroma cacao (70%), cocoa butter, organic sugar.' },
    allergens: [],
    dietaryTags: ['Dulces Tradicionales', 'Vegano', 'Sin Gluten'],
    availability: { isAvailable: true, leadTimeDays: 0 },
    ordering: { allowDirectCall: true, allowDoorDash: true, allowCustomQuote: false },
    tags: ['chocolate ecuatoriano', 'cacao fino de aroma', 'manabi', 'dulces ecuador'],
    featured: true,
    bestSeller: false,
    newProduct: true,
    seo: {
      title: { es: 'Chocolates Ecuatorianos en Orange, NJ | El Trigal', en: 'Ecuadorian Chocolates in Orange, NJ | El Trigal' },
      description: { es: 'Chocolate fino de aroma 70% de Manabí, Ecuador en Orange, NJ.', en: '70% fine aroma Manabí chocolate in Orange, NJ.' },
      keywords: ['chocolate ecuatoriano', 'cacao fino manabi orange nj'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-10',
    sku: 'BEB-CAF-01',
    name: { es: 'Café Gourmet 100% de Loja (Funda 500g Molido/Grano)', en: '100% Loja Gourmet Coffee (500g Bag Ground/Whole)' },
    slug: { es: 'cafe-gourmet-loja', en: 'loja-gourmet-coffee' },
    shortDescription: {
      es: 'Café arábigo de altura cultivado en los valles de Loja, tostado medio artesanal.',
      en: 'High-altitude Arabica coffee grown in Loja valleys, artisan medium roast.',
    },
    description: {
      es: 'El famoso café de Loja de aroma penetrante y acidez equilibrada. Grano arábigo seleccionado cultivado a más de 1,800m sobre el nivel del mar.',
      en: 'The famous Loja coffee known for intense aroma and balanced acidity. Selected Arabica beans grown above 1,800m altitude in southern Ecuador.',
    },
    primaryCategory: {
      id: 'cat-5',
      name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' },
      slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' },
    },
    categories: [
      { id: 'cat-5', name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' }, slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' } },
    ],
    productType: 'simple',
    basePriceCents: 1250,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-10',
        publicId: 'trigal/cafe-loja-1',
        secureUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Bolsa de café ecuatoriano de Loja y taza humeante', en: 'Bag of Ecuadorian Loja coffee' },
        isPrimary: true,
      },
    ],
    ingredients: { es: '100% granos de café arábigo tostado de Loja, Ecuador.', en: '100% roasted Arabica coffee beans from Loja, Ecuador.' },
    allergens: [],
    dietaryTags: ['Bebidas y Café', '100% Arábigo'],
    availability: { isAvailable: true, leadTimeDays: 0 },
    ordering: { allowDirectCall: true, allowDoorDash: true, allowCustomQuote: false },
    tags: ['cafe de loja', 'cafe ecuatoriano', 'bebidas ecuador', 'cafe pasado'],
    featured: true,
    bestSeller: true,
    newProduct: false,
    seo: {
      title: { es: 'Café Ecuatoriano de Loja en Orange, NJ | El Trigal', en: 'Ecuadorian Loja Coffee in Orange, NJ | El Trigal' },
      description: { es: 'Compra auténtico café ecuatoriano de Loja molido o en grano en Orange, NJ.', en: 'Buy authentic Loja coffee in Orange, NJ.' },
      keywords: ['cafe de loja', 'cafe ecuatoriano orange nj'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-11',
    sku: 'SNA-CHI-01',
    name: { es: 'Chifles Ecuatorianos de Plátano Verde (Funda Grande)', en: 'Ecuadorian Green Plantain Chips / Chifles (Large Bag)' },
    slug: { es: 'chifles-ecuatorianos-platano', en: 'ecuadorian-plantain-chifles' },
    shortDescription: {
      es: 'Crujientes láminas finas de plátano verde frito con sal marina o ajo.',
      en: 'Crispy thin sliced green plantain chips seasoned with sea salt or garlic.',
    },
    description: {
      es: 'El snack por excelencia de Ecuador. Chifles delgados y super crocantes preparados con plátano verde selecto de Manabí.',
      en: 'Ecuador’s ultimate snack. Super crispy thin green plantain chifles prepared with select Manabí plantains.',
    },
    primaryCategory: {
      id: 'cat-5',
      name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' },
      slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' },
    },
    categories: [
      { id: 'cat-5', name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' }, slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' } },
    ],
    productType: 'simple',
    basePriceCents: 399,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-11',
        publicId: 'trigal/chifles-1',
        secureUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Chifles ecuatorianos crocantes de plátano verde', en: 'Crispy Ecuadorian plantain chifles' },
        isPrimary: true,
      },
    ],
    ingredients: { es: 'Plátano verde ecuatoriano, aceite vegetal, sal de mar.', en: 'Ecuadorian green plantain, vegetable oil, sea salt.' },
    allergens: [],
    dietaryTags: ['Snacks y Abarrotes', 'Vegano', 'Sin Gluten'],
    availability: { isAvailable: true, leadTimeDays: 0 },
    ordering: { allowDirectCall: true, allowDoorDash: true, allowCustomQuote: false },
    tags: ['chifles ecuatorianos', 'platano verde', 'snacks ecuador', 'abarrotes ecuador'],
    featured: true,
    bestSeller: true,
    newProduct: false,
    seo: {
      title: { es: 'Chifles Ecuatorianos en Orange, NJ | El Trigal', en: 'Ecuadorian Chifles in Orange, NJ | El Trigal' },
      description: { es: 'Consigue chifles de plátano verde ecuatorianos salados en Orange, NJ.', en: 'Get crunchy green plantain chifles in Orange, NJ.' },
      keywords: ['chifles ecuatorianos', 'snacks ecuador orange nj'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-14',
    sku: 'CUI-NUT-01',
    name: { es: 'Tratamiento Capilar Nutribela 10 (Pote / Sachet)', en: 'Nutribela 10 Hair Treatment (Pot / Sachet)' },
    slug: { es: 'tratamiento-capilar-nutribela-10', en: 'nutribela-10-hair-treatment' },
    shortDescription: {
      es: 'Reparación intensiva de cabello con 10 multivitaminas y aceites naturales ecuatorianos.',
      en: 'Intensive hair repair treatment enriched with 10 multivitamins and natural oils.',
    },
    description: {
      es: 'Famoso tratamiento capilar Nutribela 10 importado directamente. Nutre, repara y devuelve el brillo natural a tu cabello con su fórmula exclusiva.',
      en: 'Famous Nutribela 10 hair treatment imported directly. Nourishes, repairs, and restores natural shine to hair.',
    },
    primaryCategory: {
      id: 'cat-5',
      name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' },
      slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' },
    },
    categories: [
      { id: 'cat-5', name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' }, slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' } },
    ],
    productType: 'simple',
    basePriceCents: 499,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-14',
        publicId: 'trigal/nutribela-1',
        secureUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Tratamiento Capilar Nutribela 10', en: 'Nutribela 10 Hair Treatment' },
        isPrimary: true,
      },
    ],
    ingredients: null,
    allergens: [],
    dietaryTags: ['Cuidado Personal', 'Importado'],
    availability: { isAvailable: true, leadTimeDays: 0 },
    ordering: { allowDirectCall: true, allowDoorDash: true, allowCustomQuote: false },
    tags: ['nutribela', 'champu', 'cuidado personal', 'tratamiento capilar', 'belleza ecuador'],
    featured: true,
    bestSeller: true,
    newProduct: true,
    seo: {
      title: { es: 'Nutribela 10 en Orange, NJ | El Trigal', en: 'Nutribela 10 in Orange, NJ | El Trigal' },
      description: { es: 'Compra tratamiento capilar Nutribela 10 importado de Ecuador en Orange, NJ.', en: 'Buy imported Nutribela 10 hair treatment in Orange, NJ.' },
      keywords: ['nutribela orange nj', 'champu ecuatoriano', 'cuidado personal ecuador'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'prod-15',
    sku: 'CUI-CHA-01',
    name: { es: 'Champú & Acondicionador Savital / Sedal Ecuatoriano', en: 'Ecuadorian Savital / Sedal Shampoo & Conditioner' },
    slug: { es: 'champu-acondicionador-savital-ecuatoriano', en: 'ecuadorian-savital-shampoo' },
    shortDescription: {
      es: 'Champú ecuatoriano con sábila natural y keratina para un cabello fuerte y brillante.',
      en: 'Ecuadorian shampoo with natural aloe vera and keratin for strong and shiny hair.',
    },
    description: {
      es: 'Champú y acondicionador tradicional importado de Ecuador con extracto de aloe vera / sábila pura. Limpieza profunda y brillo duradero.',
      en: 'Traditional shampoo & conditioner imported from Ecuador infused with natural aloe vera extract.',
    },
    primaryCategory: {
      id: 'cat-5',
      name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' },
      slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' },
    },
    categories: [
      { id: 'cat-5', name: { es: 'Productos Ecuatorianos', en: 'Ecuadorian Products' }, slug: { es: 'productos-ecuatorianos', en: 'ecuadorian-products' } },
    ],
    productType: 'simple',
    basePriceCents: 699,
    compareAtPriceCents: null,
    currency: 'USD',
    priceLabel: null,
    variants: [],
    options: [],
    media: [
      {
        id: 'med-15',
        publicId: 'trigal/champu-1',
        secureUrl: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80',
        altText: { es: 'Champú ecuatoriano Savital con Sábila', en: 'Ecuadorian Savital Shampoo' },
        isPrimary: true,
      },
    ],
    ingredients: null,
    allergens: [],
    dietaryTags: ['Cuidado Personal', 'Importado'],
    availability: { isAvailable: true, leadTimeDays: 0 },
    ordering: { allowDirectCall: true, allowDoorDash: true, allowCustomQuote: false },
    tags: ['champu', 'savital', 'nutribela', 'cuidado personal', 'belleza ecuador'],
    featured: true,
    bestSeller: false,
    newProduct: true,
    seo: {
      title: { es: 'Champú Ecuatoriano Savital en Orange, NJ | El Trigal', en: 'Ecuadorian Shampoo in Orange, NJ | El Trigal' },
      description: { es: 'Encuentra champú y acondicionador ecuatoriano Savital en Orange, NJ.', en: 'Find Ecuadorian Savital shampoo in Orange, NJ.' },
      keywords: ['champu ecuatoriano', 'savital orange nj'],
    },
    updatedAt: '2026-07-28T12:00:00Z',
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-1',
    authorName: 'María Fernanda Cárdenas',
    authorLocation: 'Orange, NJ',
    content: {
      es: '¡El mejor pan de Ambato en todo New Jersey! Las allullas y las empanadas de viento me recordaron inmediatamente a mi infancia en Ecuador.',
      en: 'The best Ambato bread in all of New Jersey! The allullas and wind empanadas immediately brought back childhood memories of Ecuador.',
    },
    rating: 5,
    date: '2026-06-15',
  },
  {
    id: 'test-2',
    authorName: 'Carlos Villacís',
    authorLocation: 'East Orange, NJ',
    content: {
      es: 'Pedimos el pastel personalizado para el bautizo de mi hija. No solo quedó precioso, sino que el bizcocho de tres leches con maracuyá fue un éxito total.',
      en: 'We ordered the custom cake for my daughter’s baptism. It looked stunning, and the passion fruit tres leches cake was an absolute hit.',
    },
    rating: 5,
    date: '2026-07-02',
  },
  {
    id: 'test-3',
    authorName: 'Jessica Miller',
    authorLocation: 'West Orange, NJ',
    content: {
      es: 'Atención cálida, pan recién horneado y café delicioso. Me encanta parar en El Trigal todas las mañanas camino al trabajo.',
      en: 'Warm customer service, fresh bread, and delicious coffee. I love stopping at El Trigal every morning on my way to work.',
    },
    rating: 5,
    date: '2026-07-20',
  },
];

export const MOCK_FAQS: FaqItem[] = [
  {
    id: 'faq-1',
    category: 'custom-cakes',
    question: {
      es: '¿Con cuánta anticipación debo pedir un pastel personalizado?',
      en: 'How far in advance should I order a custom cake?',
    },
    answer: {
      es: 'Recomendamos realizar la solicitud con al menos 3 a 5 días de anticipación para pasteles de cumpleaños, y de 1 a 2 semanas para pasteles de bodas o eventos grandes.',
      en: 'We recommend placing your order at least 3 to 5 days in advance for birthday cakes, and 1 to 2 weeks for weddings or large event cakes.',
    },
    displayOrder: 1,
  },
  {
    id: 'faq-2',
    category: 'general',
    question: {
      es: '¿A qué hora sale el pan caliente recién horneado?',
      en: 'What time is fresh hot bread available?',
    },
    answer: {
      es: 'Horneamos continuamente durante el día. La primera tanda de pan ambateño y allullas sale a las 6:00 AM, y la segunda tanda por la tarde a las 4:00 PM.',
      en: 'We bake continuously throughout the day. The first batch of Ambato bread and allullas comes out at 6:00 AM, and the second batch in the afternoon at 4:00 PM.',
    },
    displayOrder: 2,
  },
  {
    id: 'faq-3',
    category: 'orders',
    question: {
      es: '¿Hacen entregas a domicilio en Orange y alrededores?',
      en: 'Do you offer home delivery in Orange and nearby areas?',
    },
    answer: {
      es: 'Sí, puedes hacer tus pedidos para entrega a domicilio mediante DoorDash o llamando directamente a nuestra tienda al (347) 842-9351.',
      en: 'Yes, you can place delivery orders through DoorDash or by calling our bakery directly at (347) 842-9351.',
    },
    displayOrder: 3,
  },
  {
    id: 'faq-4',
    category: 'catering',
    question: {
      es: '¿Ofrecen servicio de catering y bandejas de bocaditos para fiestas?',
      en: 'Do you offer catering services and snack trays for parties?',
    },
    answer: {
      es: '¡Sí! Contamos con bandejas de empanaditas de viento, quesadillas, allullas y bocaditos dulcificados o salados para cualquier tipo de reunión social o empresarial.',
      en: 'Yes! We offer mini empanada trays, quesadillas, allullas, and assorted sweet or savory party snacks for social or corporate events.',
    },
    displayOrder: 4,
  },
];

export const MOCK_GALLERY: GalleryMediaItem[] = [
  {
    id: 'gal-1',
    publicId: 'trigal/gal-1',
    secureUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1000&auto=format&fit=crop&q=80',
    altText: { es: 'Variedad de pan ecuatoriano recién salido del horno', en: 'Assortment of fresh Ecuadorian bread from the oven' },
    title: { es: 'Horneado Diario', en: 'Daily Baking' },
    category: 'breads',
    aspectRatio: '4:3',
  },
  {
    id: 'gal-2',
    publicId: 'trigal/gal-2',
    secureUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=1000&auto=format&fit=crop&q=80',
    altText: { es: 'Pastel personalizado elegante para bodas', en: 'Elegant custom wedding cake' },
    title: { es: 'Pastel de Bodas', en: 'Wedding Cake' },
    category: 'cakes',
    aspectRatio: '1:1',
  },
  {
    id: 'gal-3',
    publicId: 'trigal/gal-3',
    secureUrl: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=1000&auto=format&fit=crop&q=80',
    altText: { es: 'Empanadas de viento recién freídas con azúcar', en: 'Freshly fried wind empanadas with sugar' },
    title: { es: 'Empanadas de Viento', en: 'Wind Empanadas' },
    category: 'pastries',
    aspectRatio: '16:9',
  },
  {
    id: 'gal-4',
    publicId: 'trigal/gal-4',
    secureUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1000&auto=format&fit=crop&q=80',
    altText: { es: 'Pastel Tres Leches con frutos rojos', en: 'Tres Leches cake with berries' },
    title: { es: 'Tres Leches Especial', en: 'Special Tres Leches' },
    category: 'cakes',
    aspectRatio: '4:3',
  },
];
